

# services:
#   app:
#     build:
#       context: .
#       dockerfile: dockerfile
#     image: docker-image
#     container_name: docker-container
#     ports:
#       - "1234:1234"
#     volumes:
#       - .:/app
#   #   working_dir: /usr/src/app
#   #   command: npm start

#   # db:
#   #   image: postgres:13
#   #   environment:
#   #     POSTGRES_USER: user
#   #     POSTGRES_PASSWORD: password
#   #     POSTGRES_DB: mydb
#   #   ports:
#   #     - "5432:5432"

#   # redis:
#   #   image: redis:6.0
#   #   ports:
#   #     - "6379:6379"

#   db:
#     image: postgres:17
#     container_name: postgres-db
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: K2362003k
#       POSTGRES_DB: docker_db
#     ports:
#       - "5432:5432"






services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-image
    container_name: app-container
    ports:
      - "8000:8000"  # غيرنا 1234 إلى 8000 ليتطابق مع Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_DB=docker_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=K2362003k
      - POSTGRES_PORT=5432

  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: K2362003k
      POSTGRES_DB: docker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: